USE C_DB10_2018

CREATE TABLE SEMINAR(
	SeminarID INT PRIMARY KEY IDENTITY(1,1), 
	SeminarDate DATE, 
	Location TEXT, 
	SeminarTitle TEXT
)

CREATE TABLE ZIP_CITY(
	Zip INT PRIMARY KEY, 
	City TEXT
)

CREATE TABLE CUSTOMER(
	CustomerID INT PRIMARY KEY IDENTITY(1,1), 
	FirstName TEXT, 
	LastName TEXT, 
	Street TEXT, 
	Zip INT
	CONSTRAINT Zip_PK FOREIGN KEY (Zip) REFERENCES ZIP_CITY(Zip)
)

CREATE TABLE SEMINAR_CUSTOMER(
	SeminarID INT, 
	CustomerID INT
	CONSTRAINT Seminar_ID_PK FOREIGN KEY (SeminarID) REFERENCES SEMINAR(SeminarID),
	CONSTRAINT Customer_ID_PK FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
)